[package]
name = "cruncher_api"
version = "0.1.0"
authors = ["Trist"]
edition = "2018"

[dependencies]
serde_json = "1.0.40"
serde = {version = "1.0.94", features = ["derive"]}
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
rocket = "0.4.2"
